name: Scheduled API Test Runs

on:
  workflow_dispatch:  # Manual trigger
  schedule:
  - cron: '0 */24 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://gudimetla-shashank.github.io/AI_Coach"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Install Allure
        run: |
          curl -o allure-2.13.8.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          sudo tar -zxvf allure-2.13.8.tgz -C /opt/
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure

      - name: Run All Java Test Files
        id: test_run
        run: |
          mvn clean test -Dtestng.xmlfiles=testng.xml

      - name: Publish Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Publish Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        id: publish_report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      # Set the GitHub Pages deployment URL with the unique workflow run number
      - name: Set Deployment URL
        if: always()  # Ensure this step runs after publishing the report
        run: |
          echo "DEPLOYMENT_URL=${{ env.BASE_URL }}/${{ github.run_number }}/#" >> $GITHUB_ENV
          echo "Deployment URL is set to ${{ env.DEPLOYMENT_URL }}"


      - name: Send Email Notification
        if: failure()   # Only send if there were test failures
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: jobs619733@gmail.com
          password: isjt npgs ozpx fxmg  # Use GitHub secret for security
          subject: 'Test Results Notification'
          body: |
            The API tests have failed. You can review the test report at the following URL:
            ${{ env.DEPLOYMENT_URL }}
          to: s96435493@gmail.com,vishal@frugaltestingin.com,yogeshk@frugaltesting.com,gudimetla@frugaltesting.com
          from: jobs619733@gmail.com
